name: update data and chart

on:
  push:
    branches: 
      - update-charts
      - main
  pull_request:
    types: [labeled]
      #schedule:
      #- cron: "0 0 * * *" # runs at 00:00 UTC everyday

jobs:
  build:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository content
        uses: actions/checkout@v1 # checkout the repository content to github runner.
      - name: Update-charts
        uses: ./.github/actions/update-charts
        
  create-bar-chart:
    needs: build
    name: Run python file to create a bar chart
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2
        
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: execute py script bars.py
        run: python scripts/bars.py
    

