name: update data and chart

on:
  pull_request:
    types: [labeled]
      #schedule:
      #- cron: "0 0 * * *" # runs at 00:00 UTC everyday

jobs:
  build:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository content
        uses: actions/checkout@v1 # checkout the repository content to github runner.

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # install the python needed
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update-charts
        uses: ./github/actions/update-charts
        id: dataChart
