name: update data and chart

on:
  pull_request:
    types: [labeled]
      #schedule:
      #- cron: "0 0 * * *" # runs at 00:00 UTC everyday

jobs:
  build:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
      - uses: JCofman/webPagetestAction@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEST_URL: https://google.com
          WEBPAGETEST_API_KEY: ${{ secrets.WEBPAGETEST_API_KEY }}
          
      - name: Checkout repository content
        uses: actions/checkout@v1 # checkout the repository content to github runner.

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # install the python needed

      - name: Update-charts
        uses: ./github/actions/update-charts
        id: dataChart
