name: update data and chart

on:
  push:
    branches:
      - main
      #schedule:
      #- cron: "0 0 * * *" # runs at 00:00 UTC everyday

jobs:
  build:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # checkout the repository content to github runner.

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # install the python needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python update.py

      - name: Update-charts
        uses: ./github/actions/update-charts
        id: dataChart

      #- name: execute py script query_data.py # run the run.py to get the latest data
      #run: |
      #python scripts/query_data.py

      - name: execute py script bars.py # run the run.py to create plot and generate .png
        run: |
          python scripts/bars.py
