name: update data and chart

on:
  push:
    branches: 
      - update-charts
  pull_request:
    types: [labeled]
      #schedule:
      #- cron: "0 0 * * *" # runs at 00:00 UTC everyday

jobs:
  build:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: Update-charts
        uses: ./.github/actions/update-charts

